[build]
  command= "npm run functions"
  functions = "functions/endpoints"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://ecommerce-ziro-bruno.netlify.app"